// docx — renders a validated decision table as a Word (.docx) document.
//
// A .docx is a ZIP archive of WordprocessingML parts. This module hand-rolls
// both layers — stored (uncompressed) ZIP entries plus the three mandatory
// parts — so the app ships no document library, in keeping with the deploy
// contract's minimal-dependency rule. Pure module: no Express, testable.

// ---------------------------------------------------------------------------
// XML
// ---------------------------------------------------------------------------

export function escXml(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
}

const FONT = '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>';

function run(text, { bold = false, italic = false, color = null, size = null } = {}) {
  const props = [
    FONT,
    bold ? "<w:b/>" : "",
    italic ? "<w:i/>" : "",
    color ? `<w:color w:val="${color}"/>` : "",
    size ? `<w:sz w:val="${size}"/><w:szCs w:val="${size}"/>` : "",
  ].join("");
  return `<w:r><w:rPr>${props}</w:rPr><w:t xml:space="preserve">${escXml(text)}</w:t></w:r>`;
}

function para(runs, { spacingAfter = 120 } = {}) {
  return `<w:p><w:pPr><w:spacing w:after="${spacingAfter}"/></w:pPr>${runs}</w:p>`;
}

// A table cell: optional shading, cell width in twips, one paragraph.
function cell(text, { width, fill = null, bold = false, color = null, size = 18 } = {}) {
  const shd = fill ? `<w:shd w:val="clear" w:color="auto" w:fill="${fill}"/>` : "";
  return [
    `<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/>${shd}<w:vAlign w:val="top"/></w:tcPr>`,
    `<w:p><w:pPr><w:spacing w:after="40"/></w:pPr>${run(text, { bold, color, size })}</w:p>`,
    "</w:tc>",
  ].join("");
}

// ---------------------------------------------------------------------------
// Document
// ---------------------------------------------------------------------------

// Landscape US Letter: 15840 x 12240 twips, 720-twip (0.5") margins leaves
// 14400 twips of usable width for the table.
const PAGE_W = 15840;
const PAGE_H = 12240;
const MARGIN = 720;
const USABLE = PAGE_W - 2 * MARGIN;

const HEADER_FILL = "1F4E79"; // dark blue header row (per the table style guide)
const LABEL_FILL = "F2F2F2"; // light gray row-label column
const BORDER = '<w:top w:val="single" w:sz="4" w:color="BFBFBF"/><w:left w:val="single" w:sz="4" w:color="BFBFBF"/><w:bottom w:val="single" w:sz="4" w:color="BFBFBF"/><w:right w:val="single" w:sz="4" w:color="BFBFBF"/><w:insideH w:val="single" w:sz="4" w:color="BFBFBF"/><w:insideV w:val="single" w:sz="4" w:color="BFBFBF"/>';

function documentXml(table) {
  const labelW = 2000;
  const optionW = Math.floor((USABLE - labelW) / table.columns.length);
  const widths = [labelW, ...table.columns.map(() => optionW)];

  const headerRow = [
    "<w:tr><w:trPr><w:tblHeader/></w:trPr>",
    cell("Decision row", { width: widths[0], fill: HEADER_FILL, bold: true, color: "FFFFFF" }),
    ...table.columns.map((c, i) => cell(c, { width: widths[i + 1], fill: HEADER_FILL, bold: true, color: "FFFFFF" })),
    "</w:tr>",
  ].join("");

  const bodyRows = table.rows.map((r) => [
    "<w:tr>",
    cell(r.label, { width: widths[0], fill: LABEL_FILL, bold: true }),
    ...r.cells.map((c, i) => cell(c, { width: widths[i + 1] })),
    "</w:tr>",
  ].join("")).join("");

  const tbl = [
    "<w:tbl><w:tblPr>",
    `<w:tblW w:w="${USABLE}" w:type="dxa"/>`,
    '<w:tblLayout w:type="fixed"/>',
    `<w:tblBorders>${BORDER}</w:tblBorders>`,
    '<w:tblCellMar><w:top w:w="60" w:type="dxa"/><w:left w:w="80" w:type="dxa"/><w:bottom w:w="60" w:type="dxa"/><w:right w:w="80" w:type="dxa"/></w:tblCellMar>',
    "</w:tblPr>",
    `<w:tblGrid>${widths.map((w) => `<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>`,
    headerRow,
    bodyRows,
    "</w:tbl>",
  ].join("");

  const body = [
    para(run(table.title, { bold: true, size: 32 }), { spacingAfter: 60 }),
    para(run("Decision question: ", { bold: true, size: 20 }) + run(table.decision_question, { size: 20 }), { spacingAfter: 40 }),
    para(run("Mode: ", { bold: true, size: 20 }) + run("Recommendation — prepared by the Chairperson of the Decision Council from the council's deliberation record.", { size: 20 }), { spacingAfter: 40 }),
    table.recommendation_preview
      ? para(run("Recommendation preview: ", { bold: true, size: 20 }) + run(table.recommendation_preview, { size: 20 }), { spacingAfter: 160 })
      : "",
    tbl,
    para(run("Generated by the PLN Decision Council. Decision support only — not legal, accounting, or financial advice.", { italic: true, size: 16 }), { spacingAfter: 0 }),
    `<w:sectPr><w:pgSz w:w="${PAGE_W}" w:h="${PAGE_H}" w:orient="landscape"/><w:pgMar w:top="${MARGIN}" w:right="${MARGIN}" w:bottom="${MARGIN}" w:left="${MARGIN}"/></w:sectPr>`,
  ].join("");

  return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    + '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
    + `<w:body>${body}</w:body></w:document>`;
}

const CONTENT_TYPES = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
  + '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
  + '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
  + '<Default Extension="xml" ContentType="application/xml"/>'
  + '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
  + "</Types>";

const RELS = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
  + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
  + '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
  + "</Relationships>";

// ---------------------------------------------------------------------------
// ZIP (stored entries only — no compression, so no external deps)
// ---------------------------------------------------------------------------

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

export function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

// entries: [{name, data: Buffer}] -> a stored-mode ZIP Buffer.
export function zipStore(entries) {
  const locals = [];
  const centrals = [];
  let offset = 0;
  for (const { name, data } of entries) {
    const nameBuf = Buffer.from(name, "utf8");
    const crc = crc32(data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0); // local file header signature
    local.writeUInt16LE(20, 4); // version needed
    local.writeUInt16LE(0, 6); // flags
    local.writeUInt16LE(0, 8); // method: stored
    local.writeUInt16LE(0, 10); // mod time
    local.writeUInt16LE(0x21, 12); // mod date (a valid constant DOS date)
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0, 28); // extra length
    locals.push(local, nameBuf, data);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0); // central dir signature
    central.writeUInt16LE(20, 4); // version made by
    central.writeUInt16LE(20, 6); // version needed
    central.writeUInt16LE(0, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0x21, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(nameBuf.length, 28);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, nameBuf);

    offset += 30 + nameBuf.length + data.length;
  }
  const centralBuf = Buffer.concat(centrals);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); // end-of-central-directory signature
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralBuf.length, 12);
  eocd.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, centralBuf, eocd]);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

// table must already have passed validateDecisionTable (council-core.mjs).
export function decisionTableDocx(table) {
  return zipStore([
    { name: "[Content_Types].xml", data: Buffer.from(CONTENT_TYPES, "utf8") },
    { name: "_rels/.rels", data: Buffer.from(RELS, "utf8") },
    { name: "word/document.xml", data: Buffer.from(documentXml(table), "utf8") },
  ]);
}
